CC*************************************************************************************************************************
CC*   Copyright (c) 2026 [Xueyu Song and Tiejun Xiao]. 
CC*  This code is distributed under the terms of the Creative Commons Attribution 4.0 International  License (CC BY 4.0).
CC*  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY.
CC*
CC*  Author: Xueyu Song
CC*  Email:   [xsong@iastate.edu]
CC*  Author: Tiejun Xiao
CC*  Email:   [tjxiao@gznc.edu.cn]
CC*  Date:    2026-10-04
CC**************************************************************************************************************************

!  chemDA.f90 
! compute the vdw interaction energy, cavity formation energy of a diatomic solute
! also compute the curvature of vertices of a surface generated by the msms code 
!  also compute the solid angle of a triangle on the molecular surface related to a site of the molecule 
! Tarea£º barycentric cell area of triangles connected to a vertex 
! Ttheta : total angle of triangles connected to a vertex 
       program chemDA
      implicit double precision (a-h, o-z)
      integer node,nedg,nele, mi,mj,mk, nc, i,j,k, i1,i2,i3, j1,j2,j3
      parameter(node=623,nele=1242,nc=5)  
      !! node is the number of vertices ,  nele is the number of faces.  
      real*8 PI,Tarea,Ttheta, area,  xsign, xss, xk1, xk2
	    real*8 f1,f2,f3,f4, Rx,Tx, phs, gama, xkappa, xkbar
      real*8 xns, dso, Eso, mucav, muvdw
      real*8  Vtot, Stot, Ctot, Xtot,Agtot
      dimension vertex(3,node), vernor(3,node), iface(3,nele)
      dimension rvf1(3,nele,node), rvf2(3,nele,node), rvf3(3,nele,node)
      dimension di(nc), rmeani(nc), uvdwi(nc)
      dimension Voi(nele,nc), rsitei(3,nc),sldi(nele,nc)
      dimension r1(3), r2(3),r3(3), rsite(3), r0(3), pij(3),dpi(3), xnorm(3)
      dimension ikey(nele), uvdw(nele),ucav(nele), dsi(nele), ha(node), gc(node)
      dimension  xCi(nele),xXi(nele) 
          PI = 3.1415926536d0
          
       open(unit=10,file='FIA.xyzr',status='old')
       open(unit=20,file='FIA.vert',status='old')
       open(unit=30,file='FIA.face',status='old')
       open(unit=40,file='FIA.curvature',status='unknown')
       open(unit=50,file='FIA.radius',status='unknown')
       open(unit=60,file='FIA.vdw',status='unknown')
       open(unit=70,file='FIA.cav',status='unknown')
       open(unit=80,file='FIA.chem',status='unknown')
 
! read the location of  two sites of the diatomic solute 
     do i=1,nc
    read(10,*) rsitei(1,i), rsitei(2,i),rsitei(3,i),di(i)
    enddo
    
!! read the location and normal of vertices       
      read(20,*)
      read(20,*)
      read(20,*)
      do i=1,node
        read(20,*)vertex(1,i),vertex(2,i),vertex(3,i), vernor(1,i),vernor(2,i),vernor(3,i),mi,mj,mk
      enddo

!! read the index of faces: n1,n2,n3 are the indexes of the faces.      
      read(30,*)
      read(30,*)
      read(30,*)
     do j=1,nele
       read(30,*)n1,n2,n3,mi,mj
        iface(1,j)=n1
        iface(2,j)=n2
        iface(3,j)=n3
     enddo  !! end for i

!! determine the face index for a fixed vertice     
!! rvf1(:,j,i), rvf2(:,j,i), rvf3(:,j,i) are the location of the three node of the j-th triangle of the i-th vertice 
     do i=1,node

        ikey(i)= 0
       do j=1,nele 
       
      if(iface(1,j)==i)then
        i1= iface(1,j)
        i2= iface(2,j)
        i3= iface(3,j)
        ikey(i)= ikey(i)+1
        rvf1(:,ikey(i),i)= vertex(:,i1)
        rvf2(:,ikey(i),i)= vertex(:,i2)
        rvf3(:,ikey(i),i)= vertex(:,i3)
       endif
        
     if(iface(2,j)==i)then
        i1= iface(2,j)
        i2= iface(3,j)
        i3= iface(1,j)
        ikey(i)= ikey(i)+1
        rvf1(:,ikey(i),i)= vertex(:,i1)
        rvf2(:,ikey(i),i)= vertex(:,i2)
        rvf3(:,ikey(i),i)= vertex(:,i3)
     endif
     
     if(iface(3,j)==i)then
        i1= iface(3,j)
        i2= iface(1,j)
        i3= iface(2,j)
        ikey(i)= ikey(i)+1
        rvf1(:,ikey(i),i)= vertex(:,i1)
        rvf2(:,ikey(i),i)= vertex(:,i2)
        rvf3(:,ikey(i),i)= vertex(:,i3)    
     endif
        
        enddo !! end for j
     enddo !! end for i
     
!! compute the Gaussian curvature and mean curvature of single vetex
!! using the total surface area of triangles connected to a vertice i, 
!! which is the 'barycentric cell area' (One third of the sum of the triangles' area adjacent to i
!! angle theta_ij is the angle of a triangle adjacent to i  
      do i=1,node
          
        Tarea=0.d0
        Ttheta=0.d0
        dpi(:)=0.d0
        xnorm(:) = vernor(:,i)

       do j=1,ikey(i) 
              
        r1(:)=  rvf1(:,j,i)
        r2(:)=  rvf2(:,j,i)
        r3(:)=  rvf3(:,j,i)
        
        call Geo_triangle(r1,r2,r3, area, theta)
        call cotan_triangle(r1,r2,r3, pij)
        Tarea = Tarea + area/3.d0
        Ttheta= Ttheta+ theta
        dpi(:)  = dpi(:)  + pij(:)
       enddo   
       

        tij= -dot_product(xnorm,dpi)
        if(tij<0.d0)then
        xsign=-1.d0
        endif
        if(tij>0.d0)then
        xsign=1.d0
        endif
        if(tij==0.d0)then
        xsign=0.d0
        endif

        gc(i)= (2*PI-Ttheta)/Tarea  !! gc is the Gaussian curvature
        ha(i)=  dsqrt(sum(dpi(1:3)**2))/4.d0/Tarea*xsign   !! ha is  the mean curvature

        xss= max(ha(i)**2-gc(i),0.d0)
        xk1= ha(i) + dsqrt(xss) !! principal curvature k1 and k2
        xk2= ha(i) - dsqrt(xss) !! principal curvature k1 and k2
        write(40,101) i, ikey(i), gc(i), ha(i)  
        write(50,102) i, 1.d0/xk1, 1.d0/xk2  !! curvature radius r1 and r2
      enddo
      
!! compute the mean distance, solid angle and vdw energy of triangles related to the sites
!! xns: particle number density of the RPM electrolyte solution 
!! Rx: gas constant, Tx: temperature 
!! ds: hard sphere diamter of the solvent 
!! eta:packing fraction
!! phs : pressure of the hard sphere fluid
!! gamma: planar surface tension of the hard sphere fluid
!! xkappa and  xkbar: two bending rigidity parameters
!! the morphological thermodynamics theory is used to determine the surface contribution to the cavity formation energy
!! dso: LJ size parameter of the solute-solvent interaction 
!! Eso LJ energy parameter of the solute-solvent interaction 
!! uvdw: vdw solvation energy due to LJ interaction
!! usurf:Hadwiger free energy, or surface contribution to the cavity formation energy, 

         xns = 0.007226d0 
         ds  = 3.215
         Rx = 8.314*1.e-3
         Tx = 300.       
         eta = xns*ds**3*PI/6. 
         f1 = (1. + eta + eta**2 -eta**3)/(1.-eta)**3 
         phs= f1*xns*Rx*Tx
         f2 = -(1. + 2.*eta +8.*eta**2 -5.*eta**3)/3./(1.-eta)**3 - Log(1.-eta)/3./eta  
         gama = f2*xns*ds/2.*Rx*Tx
         f3 = (4.-10.*eta +20.*eta**2 -8.*eta**3)/3./(1.-eta)**3 + 4.*Log(1.-eta)/3./eta
         xkappa = f3*xns*(ds/2.)**2*Rx*Tx
         f4 = (-4. + 11.*eta -13.*eta**2 +4.*eta**3)/3./(1.-eta)**3 - 4.*Log(1.-eta)/3./eta
         xkbar = f4*xns*(ds/2.)**3*Rx*Tx
         dso = 3.5d0
         Eso = 1.0d0
         
      do j=1, nele
         j1 = iface(1,j)
         j2 = iface(2,j)
         j3 = iface(3,j)
        r1(:)= vertex(:,j1)
        r2(:)= vertex(:,j2)
        r3(:)= vertex(:,j3)
        
        call Geo_triangle(r1,r2,r3, dsi(j), theta)
        hamean = (ha(j1)+ha(j2)+ha(j3))/3.     !! averaged mean curvature of the triangle
        gcmean = (gc(j1)+gc(j2)+gc(j3))/3.     !! averaged Gaussian curvature of the triangle
        xCi(j) = hamean*dsi(j)
        xXi(j) = gcmean*dsi(j)
        
        uvdw(j) =0.d0
        do k=1,nc
        rsite(:) = rsitei(:,k)
        call solid_angle(r1,r2,r3,rsite, rmeani(k),Voi(j,k), sldi(j,k))
        uvdwi(k) = 4.*xns/3.*Eso*rmeani(k)**3*((dso/rmeani(k))**12*1./3.-(dso/rmeani(k))**6) 
        uvdw(j)  = uvdw(j)+ uvdwi(k)*sldi(j,k) 
        enddo     
        ucav(j) = phs*Voi(j,1) + gama*dsi(j) + xkappa*xCi(j) + xkbar*xXi(j) !! cavity formation energy related to a triangle
        
         write(60,*) j, uvdw(j)   !! output the vdw interaction energy related to each triangle
         write(70,*) j, ucav(j)   !! output the surface energy  related to each triangle
                  
      enddo
 
!! one can check that the volume of the solute is independent of the reference point 0,
!!  i.e.,  Vtot1 =sum(Vo1(1:nele)) equals to vtot2=sum(Vo2(1:nele)) , 
!! Vo1 is evaluated with the center of site 1 as reference point 0, 
!!  Vo2 is evaluated with the center of site 2 as reference point 0.
!! the numerical value of the total solid angle is also independent of the reference point 0,
!! and is in good agreement with the theoretical value 4*PI=12.5664
         Vtot = sum(Voi(1:nele,1))  !! volume of the solute 
!		 Vtot2= sum(Vo2(1:nele,2))
       Stot = sum(dsi(1:nele))  !! surface area of the solute 
       Ctot= sum(xCi(1:nele))  !! integrated mean curvature  of the solute
       Xtot= sum(xXi(1:nele))  !! integrated Gaussian curvature of the solute
       Agtot= sum(sldi(1:nele,1)) !! total solid angle of the solute

!         mucav = phs*Vtot + gamma*Stot + xkappa*Ctot + xkbar*Xtot !! cavity formation energy  
       mucav = sum(ucav(1:nele))   !! cavity formation energy
       muvdw = sum(uvdw(1:nele))  !! vdw free energy
      write(80,103) Vtot, Stot, Ctot, Xtot, Agtot 
      write(80,*) muvdw, mucav
      
      
   101    format(I5, I3, 2f10.5)     
   102    format(I5, 2f10.5) 
   103    format(5f10.5)  

      close(70)      
      close(60)      
      close(50)
      close(40)
      close(30)
      close(20)
      close(10)

	stop
    end program chemDA

    
!! compute the area of a triange(1,2,3) with vetices 1,2,3, using Heron's formula
!! also compute the angle <213, with two edges r12 and r13 conected to vetex 1 
!! area is the area of the triange, theta is the angle <213 
!! area0 equals to area
    subroutine Geo_triangle(r1,r2,r3, area, theta)
    implicit real*8 (a-h,o-z)   
    dimension r1(3),r2(3),r3(3), C(3), r12(3),r13(3),r23(3) 
    real*8 a12,a13,a23, px, area, t0, tuv, costt, theta
    
      r12(:)= r2(:)-r1(:)
      r13(:)= r3(:)-r1(:)  
      r23(:)= r3(:)-r2(:)

      a12= dsqrt(dot_product(r12,r12))
      a13= dsqrt(dot_product(r13,r13))
      a23= dsqrt(dot_product(r23,r23))
      
!      call cross_product(r12,r13,C)
!      rc = dsqrt(dot_product(C,C))
!	  area0 = rc/2.

      px=(a12+a13+a23)/2.d0
      area= dsqrt(px*(px-a12)*(px-a13)*(px-a23))
     
      tuv= dot_product(r12,r13)  
      t0= tuv/a12/a13
      if(t0>1.d0)then  !! due to the numerical error, t0 may beyond (-1,1)
      costt=1.d0
      endif
      if(t0<-1.d0)then
      costt=-1.d0
      endif
      if(t0>=-1.d0.AND.t0<=1.d0)then
      costt= t0  !! Cos(theta), theta is the angle L213, connected to vertex 1
      endif
      theta= dacos(costt)  !! theta   
      
    return
    end


!! compute the cotangent of two angles of a triangle(1,2,3) 
!! cotb = Cot(beta), angle beta is the angle <123, with two edges r21 and r23 connected to vertex 2
!! cotc = Cot(alpha), angle alpha is the angle <132, with two edges r31 and r32 connected to vertex 3
!! pij(:) = cota*(r2(:)-r1(:)) + cotb*(r3(:)-r1(:))
   subroutine cotan_triangle(r1,r2,r3,pij)
  implicit real*8 (a-h,o-z)  
  real*8 px, area, tta, ttb
  dimension r1(3),r2(3),r3(3), pij(3)
             
       call Geo_triangle(r2,r1,r3,area, ttb)
       cotb= 1.0/tan(ttb)
       
       call Geo_triangle(r3,r1,r2,area, tta)
       cota= 1.0/tan(tta)
             
!	  write(*,*) cota, cotb   !! cota and cotb are positive values
      pij(:)=  cota*(r2(:)-r1(:)) + cotb*(r3(:)-r1(:))
      
   return
    end
    
!compute the cross product of two vectors A and B
   subroutine cross_product(A,B,C)
    implicit real*8 (a-h,o-z)
    dimension A(3),B(3),C(3)

     C(1) = A(2)*B(3)-A(3)*B(2)
     C(2) = A(3)*B(1)-A(1)*B(3)
     C(3) = A(1)*B(2)-A(2)*B(1)
   return
   end

!! compute the volume and the solid angle of tetrahedron with four vertices(0,1,2,3)  .
!! use Oosterom's formular to compute the solid angle of a triangle(1,2,3) related to a reference point 0
!! refer:A. VAN OOSTEROM AND J. STRACKEE, IEEE TRANSACTIONS ON BIOMEDICAL ENGINEERING 30,125(1983) The solid angle of a plane triangle
!  In this work, 0 is taken as a site of the diatomic solute.
! r1,r2,r3 are the location of three vetices on the triangle.
! r0 is the location of the reference point 0. 
! rmean is the mean distance between 0 and the triangle(1,2,3)
! Vo is the volume of the tetrahedron with four vertices(0,1,2,3)
!  sld is the solid angle of the triangle related to reference point 0. 
!! t0a equals to t0 
   subroutine solid_angle(r1,r2,r3,r0, rmean, Vo, sld)
   implicit real*8 (a-h,o-z)  
	 real*8 rA,rB,rC, dpAB, dpBC, dpAC, rmean, t0, t1, Vo, sld
   dimension r1(3),r2(3),r3(3), r0(3), A(3),B(3),C(3), D(3)
     
     A(:) = r1(:)-r0(:)  
     B(:) = r2(:)-r0(:)  
     C(:) = r3(:)-r0(:)  
     rA =  dsqrt(dot_product(A,A))
     rB =  dsqrt(dot_product(B,B))
     rC =  dsqrt(dot_product(C,C))
     rmean= (rA+rB+rc)/3.       !!  mean distance  
     
     dpAB = dot_product(A,B)  !! dot product of vector A and vector B
     dpAC = dot_product(A,C)  !! dot product of vector A and vector C
     dpBC = dot_product(B,C)  !! dot product of vector A and vector B

     call cross_product(A,B,D)    
!     t0a= A(1)*B(2)*C(3)+ A(2)*B(3)*C(1)+ A(3)*B(1)*C(2)- A(1)*B(3)*C(2)- A(2)*B(1)*C(3)- A(3)*B(2)*C(1)
      t0 = dot_product(D,C)   
      Vo= t0/6.
      t1 = dpAB*rC+ dpBC*rA+ dpAC*rB+ rA*rB*rC
      sld= 2.*atan2(t0,t1)      !! solid angle 
     return
     end
