!CC*************************************************************************************************************************
!CC*   Copyright (c) 2026 [Xueyu Song and Tiejun Xiao]. 
!CC*  This code is distributed under the terms of the Creative Commons Attribution 4.0 International  License (CC BY 4.0).
!CC*  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY.
!CC*
!CC*  Author: Xueyu Song
!CC*  Email:   [xsong@iastate.edu]
!CC*  Author: Tiejun Xiao
!CC*  Email:   [tjxiao@gznc.edu.cn]
!CC*  Date:    2026-10-04
!CC*************************************************************************************************************************!

!  curvature.f90 
! compute the curvature of vertices of a solute surface generated by the msms code
! the solute is a diatomic molecule. nc=2 is the number of atoms of the solute. 
! Tarea£º barycentric cell area of triangles connected to a vertex 
! Ttheta : total angle of triangles connected to a vertex 
!!  ref: https://rodolphe-vaillant.fr/entry/33/curvature-of-a-triangle-mesh-definition-and-computation

       program curvature
      implicit double precision (a-h, o-z)
      integer node,nedg,nele, mi,mj,mk, nc, i,j,k, i1,i2,i3, j1,j2,j3
      parameter(node=410,nele=816,nc=2)  
      !! node is the number of vertices ,  nele is the number of faces.  
      real*8 PI,Tarea,Ttheta, area,  xsign, xss, xk1, xk2
      real*8 f1,f2,f3,f4, Rx,Tx, phs, gama, xkappa, xkbar
      real*8 xns, dso, Eso, mucav, muvdw
      real*8  Vtot, Stot, Ctot, Xtot,Agtot
      dimension vertex(3,node), vernor(3,node), iface(3,nele)
      dimension rvf1(3,nele,node), rvf2(3,nele,node), rvf3(3,nele,node)
      dimension di(nc), rmeani(nc), uvdwi(nc)
      dimension Voi(nele,nc), rsitei(3,nc),sldi(nele,nc)
      dimension r1(3), r2(3),r3(3), rsite(3), r0(3), pij(3),dpi(3), xnorm(3)
      dimension ikey(nele), dsi(nele), ha(node), gc(node)
      dimension  xCi(nele),xXi(nele) 
          PI = 3.1415926536d0
          
       open(unit=10,file='DA5.xyzr',status='old')
       open(unit=20,file='DA5.vert',status='old')
       open(unit=30,file='DA5.face',status='old')
       open(unit=40,file='DA5.curvature',status='unknown')
 
! read the location of  two sites of the diatomic solute 
     do i=1,nc
    read(10,*) rsitei(1,i), rsitei(2,i),rsitei(3,i),di(i)
    enddo
    
!! read the location and normal of vertices       
      read(20,*)
      read(20,*)
      read(20,*)
      do i=1,node
        read(20,*)vertex(1,i),vertex(2,i),vertex(3,i), vernor(1,i),vernor(2,i),vernor(3,i),mi,mj,mk
      enddo

!! read the index of faces: n1,n2,n3 are the indexes of the faces.      
      read(30,*)
      read(30,*)
      read(30,*)
     do j=1,nele
       read(30,*)n1,n2,n3,mi,mj
        iface(1,j)=n1
        iface(2,j)=n2
        iface(3,j)=n3
     enddo  !! end for i

!! determine the face index for a fixed vertice     
!! rvf1(:,j,i), rvf2(:,j,i), rvf3(:,j,i) are the location of the three node of the j-th triangle of the i-th vertice 
     do i=1,node

        ikey(i)= 0
       do j=1,nele 
       
      if(iface(1,j)==i)then
        i1= iface(1,j)
        i2= iface(2,j)
        i3= iface(3,j)
        ikey(i)= ikey(i)+1
        rvf1(:,ikey(i),i)= vertex(:,i1)
        rvf2(:,ikey(i),i)= vertex(:,i2)
        rvf3(:,ikey(i),i)= vertex(:,i3)
       endif
        
     if(iface(2,j)==i)then
        i1= iface(2,j)
        i2= iface(3,j)
        i3= iface(1,j)
        ikey(i)= ikey(i)+1
        rvf1(:,ikey(i),i)= vertex(:,i1)
        rvf2(:,ikey(i),i)= vertex(:,i2)
        rvf3(:,ikey(i),i)= vertex(:,i3)
     endif
     
     if(iface(3,j)==i)then
        i1= iface(3,j)
        i2= iface(1,j)
        i3= iface(2,j)
        ikey(i)= ikey(i)+1
        rvf1(:,ikey(i),i)= vertex(:,i1)
        rvf2(:,ikey(i),i)= vertex(:,i2)
        rvf3(:,ikey(i),i)= vertex(:,i3)    
     endif
        
        enddo !! end for j
     enddo !! end for i
     
!! compute the Gaussian curvature and mean curvature of single vetex
!! using the total surface area of triangles connected to a vertice i, 
!! which is the 'barycentric cell area' (One third of the sum of the triangles' area adjacent to i
!! angle theta_ij is the angle of a triangle adjacent to i  
      do i=1,node
          
        Tarea=0.d0
        Ttheta=0.d0
        dpi(:)=0.d0
        xnorm(:) = vernor(:,i)

       do j=1,ikey(i) 
              
        r1(:)=  rvf1(:,j,i)
        r2(:)=  rvf2(:,j,i)
        r3(:)=  rvf3(:,j,i)
        
        call Geo_triangle(r1,r2,r3, area, theta)
        call cotan_triangle(r1,r2,r3, pij)
        Tarea = Tarea + area/3.d0
        Ttheta= Ttheta+ theta
        dpi(:)  = dpi(:)  + pij(:)
       enddo   
       

        tij= -dot_product(xnorm,dpi)
        if(tij<0.d0)then
        xsign=-1.d0
        endif
        if(tij>0.d0)then
        xsign=1.d0
        endif
        if(tij==0.d0)then
        xsign=0.d0
        endif

        gc(i)= (2*PI-Ttheta)/Tarea                                            !! gc is the Gaussian curvature
        ha(i)=  dsqrt(sum(dpi(1:3)**2))/4.d0/Tarea*xsign   !! ha is  the mean curvature

        write(40,101) i, ikey(i), gc(i), ha(i)  

      enddo
           
   101    format(I5, I3, 2f10.5)     

      close(40)
      close(30)
      close(20)
      close(10)

	stop
    end program curvature

    
!! compute the area of a triange(1,2,3) with vetices 1,2,3, using Heron's formula
!! also compute the angle <213, with two edges r12 and r13 conected to vetex 1 
!! area is the area of the triange, theta is the angle <213 
!! area0 equals to area
    subroutine Geo_triangle(r1,r2,r3, area, theta)
    implicit real*8 (a-h,o-z)   
    dimension r1(3),r2(3),r3(3), C(3), r12(3),r13(3),r23(3) 
    real*8 a12,a13,a23, px, area, t0, tuv, costt, theta
    
      r12(:)= r2(:)-r1(:)
      r13(:)= r3(:)-r1(:)  
      r23(:)= r3(:)-r2(:)

      a12= dsqrt(dot_product(r12,r12))
      a13= dsqrt(dot_product(r13,r13))
      a23= dsqrt(dot_product(r23,r23))
      
      px=(a12+a13+a23)/2.d0
      area= dsqrt(px*(px-a12)*(px-a13)*(px-a23))
     
      tuv= dot_product(r12,r13)  
      t0= tuv/a12/a13
      if(t0>1.d0)then  !! due to the numerical error, t0 may beyond (-1,1)
      costt=1.d0
      endif
      if(t0<-1.d0)then
      costt=-1.d0
      endif
      if(t0>=-1.d0.AND.t0<=1.d0)then
      costt= t0  !! Cos(theta), theta is the angle L213, connected to vertex 1
      endif
      theta= dacos(costt)   
      
    return
    end

!! compute the cotangent of two angles of a triangle(1,2,3) 
!! cotb = Cot(beta), angle beta is the angle <123, with two edges r21 and r23 connected to vertex 2
!! cota = Cot(alpha), angle alpha is the angle <132, with two edges r31 and r32 connected to vertex 3
!! pij(:) = cota*(r2(:)-r1(:)) + cotb*(r3(:)-r1(:))
   subroutine cotan_triangle(r1,r2,r3,pij)
  implicit real*8 (a-h,o-z)  
  real*8 px, area, tta, ttb
  dimension r1(3),r2(3),r3(3), pij(3)
             
       call Geo_triangle(r2,r1,r3,area, ttb)
       cotb= 1.0/tan(ttb)
       
       call Geo_triangle(r3,r1,r2,area, tta)
       cota= 1.0/tan(tta)
             
!	  write(*,*) cota, cotb   !! cota and cotb are positive values
      pij(:)=  cota*(r2(:)-r1(:)) + cotb*(r3(:)-r1(:))
      
   return
    end
    